### ISSUE TITLE
CI failing due to missing `objcopy` binary

### ISSUE THREAD

**Issue by abrestic-rivos** [rivosinc/salus#256]
From https://github.com/rivosinc/salus/actions/runs/4225276190/jobs/7337635065

```
make: ./riscv64-unknown-elf-objcopy: No such file or directory
./riscv64-unknown-elf-objcopy -O binary target/riscv64gc-unknown-none-elf/release/tellus tellus_raw
make: *** [Makefile:92: tellus_bin] Error 127
Error: Process completed with exit code 2.
```

How did this work in the first place? Can we pull in `objcopy` using something like this: https://github.com/rust-embedded/cargo-binutils ?

**Comment by abrestic-rivos** [comment]
Looks like `objcopy` gets cached via the "objdump to cache" action and the restore from cache in the CI workflow was silently failing:

```
0s
Run actions/cache/restore@v3
  with:
    path: ./riscv64-unknown-elf-objcopy
    key: objcopy
    enableCrossOsArchive: false
    fail-on-cache-miss: false
  env:
    CARGO_TERM_COLOR: always
    OBJCOPY: ./riscv6[4](https://github.com/rivosinc/salus/actions/runs/4207958247/jobs/7303410066#step:7:4)-unknown-elf-objcopy
Cache not found for input keys: objcopy
```

Manually re-running "objudmp to cache" seems to have resoled things -- does the cache expire or something?

Regardless, we need a less janky solution for using `objcopy` in the build process.
